use_frameworks!

platform :ios, '9.0'

target 'studyModule_Example' do
  pod 'studyModule', :path => '../'

  target 'studyModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
